### ISSUE TITLE
Header tenant IDs are spoof-able

### ISSUE THREAD

**Issue by kevinmichaelchen** [TeslaGov/clarakm-tenant-interceptor#1]

**Comment by fitzyjoe** [comment]
Should we put the tenant ID in the JWT?

**Comment by kevinmichaelchen** [comment]
Doesn’t that mean you won’t be able to switch between tenants without re-acquiring a new JWT (i.e. logging in)?

**Comment by kevinmichaelchen** [comment]
It’s a tradeoff between forced logins and non-spoof-ability. I’m fairly certain Slack lets you switch from one tenant to another without requiring a new login.

**Comment by fitzyjoe** [comment]
I think it should require a different user account. User accounts should exist in the context of a tenant. Rampart should be multi tenant to support this. I have accounts with different gmail tenants and I have to login to them separately.

**Comment by kevinmichaelchen** [comment]
Makes sense. I will make changes so that the next version will expect a tenant ID in the JWT.
